# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'test2.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.7
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets

import bluetooth

class Ui_StartingPage(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_Button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.searching())
        self.search_Button.setGeometry(QtCore.QRect(20, 30, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_Button.setFont(font)
        self.search_Button.setObjectName("search_Button")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(20, 200, 221, 131))
        self.button_2.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(20, 370, 221, 131))
        # self.button_3.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget, itemClicked = lambda: self.presentButton())
        self.listWidget.setGeometry(QtCore.QRect(280, 70, 511, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def searching(self):

        #Clear CURRENT LIST !!!!!!!!!!!!!!!!!!!!!!!!!!!!


        # self.label.setText("Searching for nearby devices .... ")
        
        nearby_devices = bluetooth.discover_devices(
            duration=2, lookup_names=True, flush_cache=True, lookup_class=False)

        #print("found %d device(s)" % len(nearby_devices))
        self.label.setText("found %d device(s)" % len(nearby_devices))
        my_list = []
        i = 1
        for addr, name in nearby_devices:    
            try:
                #print("  %s - %s" % (addr, name))
                my_list.append(["INDEX: " + str(i), "NAME: " + name, "Address: " +  addr])
                i += 1
            except UnicodeEncodeError:
                #print("  %s - %s" % (addr, name.encode('utf-8', 'replace')))
                my_list.append(["INDEX: " + str(i) , "NAME: " + name.encode('utf-8', 'replace'),"Address: " +  addr])
                i += 1

        for element in my_list:
            #print(element)
            self.listWidget.addItem(str(element))

    def presentButton(self):
        self.button_2.setEnabled(True)
        
    def hostServer(self):
        self.hide()
        
        #Open another window.
        #Hide this window
    
    #def connectToServer(self):
        #Attempt connection
        #If Successfull
            #Open other window with connection
        #else
            #print connection failed


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_Button.setText(_translate("MainWindow", "Search For\n"
" Bluetooth Devices"))
        self.button_2.setText(_translate("MainWindow", "Attempt Connection\n"
" to Selected Device"))
        self.button_3.setText(_translate("MainWindow", "Host Server"))
        self.label.setText(_translate("MainWindow", "Nearby Devices"))